# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS17_UITraitCollection' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'GGXSwiftExtension'
  # Pods for iOS17_UITraitCollection

end
